### ISSUE TITLE
Makefile

### ISSUE THREAD

**Issue by tansy** [gitGNU/objconv#6]
There is no makefile in repo so I decided to cook one.

[Makefile.gz](https://github.com/gitGNU/objconv/files/4052815/Makefile.gz)

**Comment by ralic** [comment]
Added it, you may want to send a pull request next time.

**Comment by tansy** [comment]
When I learn how to do that I will :) I'm not good with git, it's kind of peculiar but I can deal with it. I will have to learn it after all.
